Models/Employee.cs
namespace FlexiTime.Models
{
    public class Employee
    {
        public Employee()
        {
            
        }
        public Employee(int id, string forename, string surname, Location office, string email)
        {
            this.id = id;
            this.Forename = forename;
            this.Surname = surname;
            this.HomeOffice = office;
            this.Email = email;
        }
        private int id;

        public int EmployeeID
        {
            get
            {
                return this.id;
            }
        }
        public string Forename{get;set;}
        public string Surname{get;set;}
        public Location HomeOffice{get;set;}
        public string Email{get;set;}

        public string FormattedName()
        {
            return Forename + " " + Surname;
        }
    }
}

Models/Location.cs
namespace FlexiTime.Models
{
    public class Location
    {
        public Location(int id, string name)
        {
            this.id = id;
            this.Name = name;
        }
        private int id;
        public int LocationID
        {
            get
            {
                return this.id;
            }
        }
        public string Name{get;set;}
    }
}

Models/Team.cs
using System.Collections.Generic;

namespace FlexiTime.Models
{
    public class Team
    {
        public Team(int id, string name, List<Employee> members)
        {
            this.id = id;
            this.Name = name;
            this.Members = members;
        }
        private int id;

        public int TeamID{
            get
            {
                return this.id;
            }
        }
        public string Name{get;set;}

        public List<Employee> Members{get;set;}

        public List<string> GetMemberNames()
        {
            var names = new List<string>();
            foreach(var member in Members)
            {
                names.Add(member.FormattedName());
            }
            return names;
        }
    }
}

ViewModels/EmployeeViewModel.cs
using FlexiTime.Models;

namespace FlexiTime.ViewModels
{
    public class EmployeeViewModel
    {
        public int Id{get;set;}
        public string Name{get;set;}
        public string Forename{get;set;}
        public string Surname{get;set;}
        public string Email{get;set;}
        public string HomeOffice{get;set;}

        public EmployeeViewModel(Employee employee)
        {
            this.Id = employee.EmployeeID;
            this.Forename = employee.Forename;
            this.Surname = employee.Surname;
            this.Name = employee.FormattedName();
            this.Email = employee.Email;
        }
    }
}

ViewModels/LocationViewModel.cs
namespace FlexiTime.ViewModels
{
    public class LocationViewModel
    {
        public string Name{get;set;}
    }

}

ViewModels/TeamViewModel.cs
using System.Collections.Generic;

namespace FlexiTime.ViewModels
{
    public class TeamViewModel
    {
        public string Name{get;set;}
        public List<string> Members{get;set;}
        
    }
}

Controllers/EmployeesController.cs
using FlexiTime.Data;
using Microsoft.AspNetCore.Mvc;
using FlexiTime.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;
using FlexiTime.Models;

namespace FlexiTime.Controllers
{

    public class EmployeesController : Controller
    {
        IEmployeeData _employeeData = new EmployeeData();
        
        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            return View(await Task.Run(() => GetEmployeeViewModelList(id)));   
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View(await Task.Run(() =>  _employeeData.GetEmployeeById(id)));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Employee employee)
        {
            _employeeData.UpdateEmployee(employee);
            
            return await Task.Run(() => RedirectToAction("Index"));
        }

        private List<EmployeeViewModel> GetEmployeeViewModelList(string SearchTerm)
        {
            var employees = new List<EmployeeViewModel>();

            foreach (var employee in _employeeData.GetEmployeesByName(SearchTerm))
            {
                EmployeeViewModel employeeViewModel = new EmployeeViewModel(employee);
                
                employees.Add(employeeViewModel);
            }

            return employees;
        }

        private EmployeeViewModel GetEmployeeViewModelFromID(int id)
        {
            var employee = _employeeData.GetEmployeeById(id);

            var employeeViewModel = new EmployeeViewModel(employee);

            return employeeViewModel;
        }
    }
}

Controllers/HomeController.cs
using FlexiTime.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FlexiTime.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {

        }
        public IActionResult Index()
        {
            // var homeViewModel = new HomeViewModel();

            //return View(homeViewModel);
            return View();
        }

        // public string Index()
        // {
        //     return "home controller";
        // }

    }
}

Controllers/LocationsController.cs
using Microsoft.AspNetCore.Mvc;
using FlexiTime.Data;
using System.Threading.Tasks;
using System.Collections.Generic;
using FlexiTime.ViewModels;

namespace FlexiTime.Controllers
{
    public class LocationsController : Controller
    {
        ILocationData _locationData = new LocationData();

        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            
            return View(await Task.Run(() => GetLocationViewModelList(id)));

        }

        private List<LocationViewModel> GetLocationViewModelList(string searchTerm)
        {
            var locationViewModels = new List<LocationViewModel>();

            foreach(var location in _locationData.GetLocationsByName(searchTerm))
            {
                var locationViewModel = new LocationViewModel();
                locationViewModel.Name = location.Name;
                locationViewModels.Add(locationViewModel);
            }

            return locationViewModels;
        }
    }
}

Controllers/TeamsController.cs
using FlexiTime.ViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using FlexiTime.Data;
using System.Threading.Tasks;

namespace FlexiTime.Controllers
{
    public class TeamsController : Controller
    {
        ITeamData _teamData = new TeamData();
        
        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            return View(await Task.Run(() => GetTeamsViewModelList(id)));
        }

        private List<TeamViewModel> GetTeamsViewModelList(string searchTerm)
        {
            var teams = new List<TeamViewModel>();
            foreach(var team in _teamData.GetTeamsByName(searchTerm))
            {
                var teamViewModel = new TeamViewModel();
                teamViewModel.Name = team.Name;
                teamViewModel.Members = team.GetMemberNames();
                teams.Add(teamViewModel);
            }
            return teams;

        }
    }

}

Views/Employees/Edit.cshtml
@model FlexiTime.Models.Employee

<form method="post">

    <h2>Edit @Model.FormattedName()</h2>

      <div class="control-group">
         <label class="control-label" for="Forename">Forename</label>
         <div class="controls">
            <input class="text-box single-line" data-val="true" id="Forename" name="Forename" type="text" />
            <span class="field-validation-valid help-inline" data-valmsg-for="Forename"></span>
         </div>
      </div>


    <div class="form-actions">
        <input type="submit" value="Save" class="btn" />
    </div>
</form>

Views/Employees/Index.cshtml
@model IEnumerable<FlexiTime.ViewModels.EmployeeViewModel>

<h2>Employees</h2>
 
<form asp-controller="Employees" asp-action="Index" method="get">
    <p>
        <input type="text" name="id">
        <input type="submit" value="Filter by name" />
    </p>
</form>

@foreach(var employee in Model)
{
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@employee.Name</h3>
            </div>
            <div class="panel-body">
                <span>Home Office: @employee.HomeOffice</span>
                <span>Email: @employee.Email</span>
                <a asp-controller="Employees" asp-action="Edit" asp-route-id="@employee.Id">Edit</a>
            </div>
        </div>
    </div>
}

Views/Home/Index.cshtml
@page
@{

}


<div>
    <h1>Hi</h1>
</div>

Views/Locations/Index.cshtml
@model IEnumerable<FlexiTime.ViewModels.LocationViewModel>

<h2>Locations</h2>
 
<form asp-controller="Locations" asp-action="Index" method="get">
    <p>
        <input type="text" name="id">
        <input type="submit" value="Filter by name" />
    </p>
</form>

@foreach(var location in Model)
{
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@location.Name</h3>
            </div>
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Flexitime</title>

        <link rel="stylesheet" 
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
                crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: #4f91b7">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Flexitime</a>
            <button class="navbar-toggler" 
                    type="button" 
                    data-toggle="collapse" 
                    data-target="#navbarSupportedContent" 
                    aria-controls="navbarSupportedContent" 
                    aria-expanded="false" 
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav flex-grow-1">
                    <li><a class="nav-link text-dark" asp-controller="Employees" asp-action="Index">Employees</a></li>
                    <li><a class="nav-link text-dark" asp-controller="Teams" asp-action="Index">Teams</a></li>
                    <li><a class="nav-link text-dark" asp-controller="Locations" asp-action="Index">Locations</a></li>
                </ul>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
                crossorigin="anonymous"></script>

        @RenderSection("Scripts", required: false)
    </body>
</html>